.\"                                      Hey, EMACS: -*- nroff -*-
.TH NSS-PASSWORDS 1 "April 2011"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
nss-passwords \- read passwords from Mozilla keyrings from command line
.SH SYNOPSIS
.B nss-passwords
.RI [ options ] " query"
.SH DESCRIPTION
This manual page documents briefly the
.B nss-passwords
command.
.PP
\fBnss-passwords\fP is a program that reads passwords from keyrings
used by Mozilla products, like Firefox and Thunderbird. It can run
entirely in text mode. \fIquery\fP is a string that will be looked for
in the hostname entries of the keyring.
.SH OPTIONS
.TP
.B \-d \fIdir
Profile directory. By default, Firefox default profile is guessed.
.TP
.B \-p \fIprog
Program used to ask for a password. By default, \fBpinentry\fP(1) is used.
.TP
.B \-help, \-\-help
Show summary of options.
.SH SEE ALSO
.BR pinentry (1).
.SH AUTHOR
nss-passwords was written by Stéphane Glondu <steph@glondu.net>.
